# GitHub Pages Configuration
title: Kerala Mangrove Species Segmentation
description: AI-powered identification of 19 native Kerala mangrove species for DJI Mini 2 drone footage
url: "https://your-username.github.io"
baseurl: "/kerala-mangrove-segmentation"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - LICENSE

# Include files
include:
  - _redirects

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Site metadata
author: Your Name
email: your-email@example.com
github_username: your-username

# SEO
google_analytics: UA-XXXXXXXX-X
